Refine comments

diff --git a/mgmt/bootstrap b/mgmt/bootstrap
--- a/mgmt/bootstrap
+++ b/mgmt/bootstrap
@@ -4,6 +4,17 @@ REALPATH=$(realpath $0)
 WORK_DIR=$(cd $(dirname $REALPATH) && pwd)
 echo "Run srs-terraform at $WORK_DIR from $0"
 
+# Setup the UDP kernel options before restart
+# See https://www.jianshu.com/p/6d4a89359352
+# TODO: FIXME: REMOVE-NEXT-RELEASE: Setup the kernel options by the image itself.
+if [[ ! -d /usr/local/srs-terraform && $(uname -s) != 'Darwin' ]]; then
+    sudo sysctl net.core.rmem_max=16777216 &&
+    sudo sysctl net.core.rmem_default=16777216 &&
+    sudo sysctl net.core.wmem_max=16777216 &&
+    sudo sysctl net.core.wmem_default=16777216
+  if [[ $? -ne 0 ]]; then echo "Setup the UDP kernel options failed"; exit 1; fi
+fi
+
 APP_ARGS=$@
 echo "Program args: $APP_ARGS"
 
