Refine upgrade, log lost changes to log

diff --git a/mgmt/upgrade b/mgmt/upgrade
--- a/mgmt/upgrade
+++ b/mgmt/upgrade
@@ -25,6 +25,18 @@ git branch -vva &&
 ls -lh
 if [[ $? -ne 0 ]]; then echo "Prepare upgrade failed"; exit 1; fi
 
+if [[ ! -d /usr/local/srs-terraform && $(uname -s) == 'Darwin' ]]; then
+  echo "Directly finish upgrade for macOS development"
+  exit 0
+fi
+
+# Try git stash first, ignore any error.
+git stash 2>>upgrade.error.log
+if [[ $? -ne 0 ]]; then
+  echo "Warning: git stash failed, lost changes, see $(pwd)/upgrade.error.log for details";
+  git status >>upgrade.error.log
+fi
+
 echo "Upgrade code files"
 git checkout . &&
 git pull &&
