Add test for upgrade

diff --git a/mgmt/upgrade_living b/mgmt/upgrade_living
--- a/mgmt/upgrade_living
+++ b/mgmt/upgrade_living
@@ -5,13 +5,15 @@
 
 # We must setup the redis to listen at lo and eth0, to allow containers to access it.
 # Note that should never listen at * for security reason.
-PIPV4=$(ifconfig eth0 |grep 'inet ' |awk '{print $2}')
-if [[ $PIPV4 == '' ]]; then echo 'No private IP of eth0'; exit 1; fi
-# Replace the bind for redis.
-sed -i "s/^bind 127.0.0.1.*$/bind 127.0.0.1 $PIPV4/g" /etc/redis.conf && grep '^bind 127.0.0.1' /etc/redis.conf &&
-systemctl restart redis && systemctl status redis &&
-echo "Change redis to listen at lo and eth0=$PIPV4"
-if [[ $? -ne 0 ]]; then echo "Listen at eth0=$PIPV4 for redis failed"; exit 1; fi
+if [[ -f /etc/redis.conf ]]; then
+  PIPV4=$(ifconfig eth0 |grep 'inet ' |awk '{print $2}')
+  if [[ $PIPV4 == '' ]]; then echo 'No private IP of eth0'; exit 1; fi
+  # Replace the bind for redis.
+  sed -i "s/^bind 127.0.0.1.*$/bind 127.0.0.1 $PIPV4/g" /etc/redis.conf && grep '^bind 127.0.0.1' /etc/redis.conf &&
+  systemctl restart redis && systemctl status redis &&
+  echo "Change redis to listen at lo and eth0=$PIPV4"
+  if [[ $? -ne 0 ]]; then echo "Listen at eth0=$PIPV4 for redis failed"; exit 1; fi
+fi
 
 # Update the sysctl
 #   update_sysctl config value empty-line-prefix description
