Refine living upgrade script, stable v1.0.55

diff --git a/mgmt/upgrade_living b/mgmt/upgrade_living
--- a/mgmt/upgrade_living
+++ b/mgmt/upgrade_living
@@ -59,3 +59,25 @@ if [[ $(uname -s) != 'Darwin' ]]; then
   if [[ $? -ne 0 ]]; then echo "Setup the UDP kernel options failed"; exit 1; fi
 fi
 
+echo "Make and upgrade updates"
+(cd .. && make upgrade)
+if [[ $? -ne 0 ]]; then echo "Make and install updates failed"; exit 1; fi
+
+echo "Switch to new version"
+(cd ui && TMP_BUILD="build-$(date +%s)" && mv build $TMP_BUILD && mv upgrade build && rm -rf $TMP_BUILD)
+if [[ $? -ne 0 ]]; then echo "Switch to new version failed"; exit 1; fi
+
+# Change permissions before restart.
+if [[ $(id -un lighthouse 2>/dev/null) == 'lighthouse' ]]; then
+  echo "Change permissions for generated files"
+  chown -R lighthouse:lighthouse /usr/local/lighthouse/softwares &&
+  chown -R lighthouse:lighthouse /usr/local/srs-terraform
+  if [[ $? -ne 0 ]]; then echo "Change owner failed"; exit 1; fi
+fi
+
+echo "Restart service"
+systemctl daemon-reload && systemctl restart srs-terraform
+if [[ $? -ne 0 ]]; then echo "Restart service failed"; exit 1; fi
+
+echo "Living upgrade OK"
+
