Remove unnecessary symbolic links.

diff --git a/platform/auto/start_redis b/platform/auto/start_redis
--- a/platform/auto/start_redis
+++ b/platform/auto/start_redis
@@ -10,33 +10,31 @@ cd ${WORK_DIR}
 echo "Start Redis server, WORK_DIR:${WORK_DIR}"
 
 # Get the metadata of machine.
-if [[ -f ${WORK_DIR}/.env ]]; then source ${WORK_DIR}/.env; fi
+if [[ -f ${WORK_DIR}/containers/data/config/.env ]]; then source ${WORK_DIR}/containers/data/config/.env; fi
 echo "LoadEnv CLOUD=$CLOUD REGION=$REGION, SOURCE=$SOURCE"
 
-if [[ -f /etc/redis/redis.conf ]]; then
-  REDIS_PARAMS="/etc/redis/redis.conf --daemonize yes"
-  if [[ ! -z $REDIS_PASSWORD ]]; then REDIS_PARAMS="${REDIS_PARAMS} --requirepass $REDIS_PASSWORD"; fi
-  if [[ ! -z $REDIS_PORT ]]; then REDIS_PARAMS="${REDIS_PARAMS} --port $REDIS_PORT"; fi
+REDIS_PARAMS="${WORK_DIR}/containers/conf/redis.conf --daemonize yes"
+if [[ ! -z $REDIS_PASSWORD ]]; then REDIS_PARAMS="${REDIS_PARAMS} --requirepass $REDIS_PASSWORD"; fi
+if [[ ! -z $REDIS_PORT ]]; then REDIS_PARAMS="${REDIS_PARAMS} --port $REDIS_PORT"; fi
 
-  mkdir -p /data/redis
-  REDIS_PARAMS="${REDIS_PARAMS} --dir /data/redis"
-  echo "Run redis-server $REDIS_PARAMS"
+mkdir -p /data/redis
+REDIS_PARAMS="${REDIS_PARAMS} --dir /data/redis"
+echo "Run redis-server $REDIS_PARAMS"
 
-  mkdir -p /var/run/redis &&
-  redis-server $REDIS_PARAMS &&
-  REDIS_PID_FILE="/var/run/redis/redis-server.pid"
-  if [[ $? -ne 0 ]]; then echo "Start redis failed"; exit 1; fi
+mkdir -p /var/run/redis &&
+redis-server $REDIS_PARAMS &&
+REDIS_PID_FILE="/var/run/redis/redis-server.pid"
+if [[ $? -ne 0 ]]; then echo "Start redis failed"; exit 1; fi
 
-  for ((i=0; i<10; i++)); do
-    if [[ -f $REDIS_PID_FILE ]]; then
-      ps -p `cat $REDIS_PID_FILE` 1>/dev/null 2>/dev/null &&
-      echo "Redis server started, pid=`cat $REDIS_PID_FILE`" &&
-      break
-    fi
-    sleep 0.3
-  done
-
-  ps -p `cat $REDIS_PID_FILE` 1>/dev/null 2>/dev/null
-  if [[ $? -ne 0 ]]; then echo "Check redis failed"; exit 1; fi
+for ((i=0; i<10; i++)); do
+if [[ -f $REDIS_PID_FILE ]]; then
+  ps -p `cat $REDIS_PID_FILE` 1>/dev/null 2>/dev/null &&
+  echo "Redis server started, pid=`cat $REDIS_PID_FILE`" &&
+  break
 fi
+sleep 0.3
+done
+
+ps -p `cat $REDIS_PID_FILE` 1>/dev/null 2>/dev/null
+if [[ $? -ne 0 ]]; then echo "Check redis failed"; exit 1; fi
 
diff --git a/platform/auto/start_srs b/platform/auto/start_srs
--- a/platform/auto/start_srs
+++ b/platform/auto/start_srs
@@ -10,28 +10,25 @@ cd ${WORK_DIR}
 echo "Start SRS server, WORK_DIR:${WORK_DIR}"
 
 # Get the metadata of machine.
-if [[ -f ${WORK_DIR}/.env ]]; then source ${WORK_DIR}/.env; fi
+if [[ -f ${WORK_DIR}/containers/data/config/.env ]]; then source ${WORK_DIR}/containers/data/config/.env; fi
 echo "LoadEnv CLOUD=$CLOUD REGION=$REGION, SOURCE=$SOURCE"
 
-if [[ -d /usr/local/srs ]]; then
-  SRS_PARAMS="-c /usr/local/srs/conf/lighthouse.conf"
-  echo "Run srs-server $SRS_PARAMS"
+SRS_PARAMS="-c ${WORK_DIR}/containers/conf/srs.release.conf"
+echo "Run srs-server $SRS_PARAMS"
 
-  # Current directory should be /usr/local/srs-cloud/platform
-  /usr/local/srs/objs/srs $SRS_PARAMS &&
-  SRS_PID_FILE="./objs/srs.pid"
-  if [[ $? -ne 0 ]]; then echo "Start SRS failed"; exit 1; fi
+# Current directory should be /usr/local/srs-cloud/platform
+/usr/local/srs/objs/srs $SRS_PARAMS &&
+SRS_PID_FILE="./objs/srs.pid"
+if [[ $? -ne 0 ]]; then echo "Start SRS failed"; exit 1; fi
 
-  for ((i=0; i<10; i++)); do
-    if [[ -f $SRS_PID_FILE ]]; then
-      ps -p `cat $SRS_PID_FILE` 1>/dev/null 2>/dev/null &&
-      echo "SRS server started, pid=`cat $SRS_PID_FILE`" &&
-      break
-    fi
-    sleep 0.3
-  done
-
-  ps -p `cat $SRS_PID_FILE` 1>/dev/null 2>/dev/null
-  if [[ $? -ne 0 ]]; then echo "Check SRS failed"; exit 1; fi
+for ((i=0; i<10; i++)); do
+if [[ -f $SRS_PID_FILE ]]; then
+  ps -p `cat $SRS_PID_FILE` 1>/dev/null 2>/dev/null &&
+  echo "SRS server started, pid=`cat $SRS_PID_FILE`" &&
+  break
 fi
+sleep 0.3
+done
 
+ps -p `cat $SRS_PID_FILE` 1>/dev/null 2>/dev/null
+if [[ $? -ne 0 ]]; then echo "Check SRS failed"; exit 1; fi
