Redis: Check config foreach run

diff --git a/mgmt/auto/foreach_run b/mgmt/auto/foreach_run
--- a/mgmt/auto/foreach_run
+++ b/mgmt/auto/foreach_run
@@ -17,3 +17,10 @@ if [[ MEM_TOTAL -lt 2097152 ]]; then
 fi
 if [[ $? -ne 0 ]]; then echo "Create swap failed"; exit 1; fi
 
+# We must setup the redis to listen at lo and eth0, to allow containers to access it.
+# Note that should never listen at * for security reason.
+if [[ -f /etc/redis.conf ]]; then
+  bash auto/setup_redis
+  if [[ $? -ne 0 ]]; then echo "Setup redis failed"; exit 1; fi
+fi
+
