Platform: Run redis in docker.

diff --git a/mgmt/auto/foreach_run b/mgmt/auto/foreach_run
--- a/mgmt/auto/foreach_run
+++ b/mgmt/auto/foreach_run
@@ -2,26 +2,13 @@
 
 echo "Foreach run script"
 
-# If memory smaller than 2GB, create swap to avoid OOM, please see
-# https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-18-04
-#
-# Note that another solution is to disable GENERATE_SOURCEMAP to avoid OOM, but it doesn't work sometimes, please see
-# https://create-react-app.dev/docs/advanced-configuration/
-#
-# Disable swap by: swapoff /srs-swapfile
-MEM_TOTAL=$(grep MemTotal /proc/meminfo |awk '{print $2}')
-if [[ $MEM_TOTAL -lt 2097152 ]]; then
-  swapon --show |grep "/srs-swapfile"
-  if [[ $? -ne 0 ]]; then
-    rm -rf /srs-swapfile && fallocate -l 2G /srs-swapfile && chmod 600 /srs-swapfile && ls -lh /srs-swapfile &&
-    mkswap /srs-swapfile && swapon /srs-swapfile && echo "Create swap /srs-swapfile for MEM_TOTAL=$MEM_TOTAL"
-  fi
+# Disable the swap, after migrate platform to docker.
+if [[ -f /srs-swapfile ]]; then
+  swapoff /srs-swapfile && rm -rf /srs-swapfile
+  if [[ $? -ne 0 ]]; then echo "Disable swap failed"; exit 1; fi
 fi
-if [[ $? -ne 0 ]]; then echo "Create swap failed"; exit 1; fi
 
-# We must setup the redis to listen at lo and eth0, to allow containers to access it.
-# Note that should never listen at * for security reason.
-# Note that we must check redis config for each run, to regenerate the config if corrupt.
+# Revert the redis config, after migrate to docker.
 if [[ -f /etc/redis.conf || -f /etc/redis/redis.conf ]]; then
   bash auto/setup_redis
   if [[ $? -ne 0 ]]; then echo "Setup redis failed"; exit 1; fi
diff --git a/mgmt/auto/setup_redis b/mgmt/auto/setup_redis
--- a/mgmt/auto/setup_redis
+++ b/mgmt/auto/setup_redis
@@ -1,70 +1,57 @@
 #!/usr/bin/env bash
 
-# Detect the private IPv4 address, try eth1, then eth0.
-# For droplet, the eth0 is public network.
-PIPV4=$(ifconfig eth1 2>/dev/null |grep 'inet ' |awk '{print $2}')
-if [[ -z $PIPV4 ]]; then PIPV4=$(ifconfig eth0 2>/dev/null |grep 'inet ' |awk '{print $2}'); fi
-if [[ -z $PIPV4 ]]; then echo 'No private IP of eth0'; exit 1; fi
-
 # For CentOS 7, it's /etc/redis.conf
 # For Ubuntu 20, it's /etc/redis/redis.conf
 REDIS_CONF=/etc/redis.conf
 if [[ ! -f $REDIS_CONF ]]; then REDIS_CONF=/etc/redis/redis.conf; fi
 if [[ ! -f $REDIS_CONF ]]; then echo "no redis config"; exit 1; fi
 
+# If redis also listen at 56379, stop it.
+grep -q "^port 56379" $REDIS_CONF; STOP_REDIS=$?
+systemctl status redis > /dev/null; REDIS_ALIVE=$?
+if [[ $STOP_REDIS -eq 0 && $REDIS_ALIVE -eq 0 ]]; then
+  systemctl stop redis; if [[ $? -ne 0 ]]; then echo "Stop redis failed"; exit 1; fi
+fi
+
 # Always write all cli tools to /root
 # Note that it's not required tool, so we only need a place to save the script.
 REDIS_CLI=/root/redis-cli
 API_SECRET_CLI=/root/api-secret
-echo "Setup redis script, PrivateIPv4=$PIPV4, REDIS_CONF=${REDIS_CONF}, REDIS_CLI=${REDIS_CLI}, API_SECRET_CLI=${API_SECRET_CLI}"
+echo "Setup redis script, REDIS_CONF=${REDIS_CONF}, REDIS_CLI=${REDIS_CLI}, API_SECRET_CLI=${API_SECRET_CLI}"
 
-# Replace the bind for redis.
-grep -q "^bind 127.0.0.1 $PIPV4" $REDIS_CONF; SETUP_BIND=$?
-if [[ $SETUP_BIND -ne 0 ]]; then
-  sed -i "s/^bind 127.0.0.1.*$/bind 127.0.0.1 $PIPV4/g" $REDIS_CONF &&
-  grep "^bind 127.0.0.1" $REDIS_CONF &&
-  echo "Change redis to listen at lo and $PIPV4"
-  if [[ $? -ne 0 ]]; then echo "Listen at $PIPV4 for redis failed"; exit 1; fi
+# Save host to .env
+grep -q "^REDIS_HOST=" .env; REDIS_HOST=$?
+if [[ $REDIS_HOST -ne 0 ]]; then
+  echo "REDIS_HOST=redis" >> .env && echo "Setup REDIS_HOST=redis ok"
+  if [[ $? -ne 0 ]]; then echo "Setup REDIS_HOST failed"; exit 1; fi
 fi
 
 # Save port to .env
 grep -q "^REDIS_PORT=" .env; SETUP_PORT=$?
 if [[ $SETUP_PORT -ne 0 ]]; then
-  echo "REDIS_PORT=56379" >> .env &&
-  sed -i "s/^port 6379.*$/port 56379/g" $REDIS_CONF &&
-  echo "Listen to port 56379"
-  if [[ $? -ne 0 ]]; then echo "Change listen port failed"; exit 1; fi
+  echo "REDIS_PORT=56379" >> .env && echo "Setup REDIS_PORT=56379 ok"
+  if [[ $? -ne 0 ]]; then echo "Setup REDIS_PORT failed"; exit 1; fi
 fi
 
 # Save password to .env
 grep -q "^REDIS_PASSWORD=" .env; SETUP_PASSWORD=$?
 if [[ $SETUP_PASSWORD -ne 0 ]]; then
   REDIS_PASSWORD=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)
-  echo "REDIS_PASSWORD=${REDIS_PASSWORD}" >> .env
-  sed -i "s/.*requirepass .*$/requirepass $REDIS_PASSWORD/g" $REDIS_CONF &&
-  echo "Set redis password"
-  if [[ $? -ne 0 ]]; then echo "Change password failed"; exit 1; fi
-fi
-
-if [[ $SETUP_BIND -ne 0 || $SETUP_PORT -ne 0 || $SETUP_PASSWORD -ne 0 ]]; then
-  echo "Wait for a while for upgrade to query and change status" && sleep 10 &&
-  systemctl restart redis && systemctl status redis && echo "Restart redis"
-  if [[ $? -ne 0 ]]; then echo "Restart redis failed"; exit 1; fi
+  echo "REDIS_PASSWORD=${REDIS_PASSWORD}" >> .env && echo "Setup REDIS_PASSWORD ok"
+  if [[ $? -ne 0 ]]; then echo "Setup REDIS_PASSWORD failed"; exit 1; fi
 fi
 
 if [[ ! -z $REDIS_CLI ]]; then
   echo '#!/usr/bin/env bash' > $REDIS_CLI &&
   cat .env |grep REDIS >> $REDIS_CLI &&
   echo "redis-cli -p \$REDIS_PORT -a \$REDIS_PASSWORD \$*" >> $REDIS_CLI &&
-  chmod +x $REDIS_CLI &&
-  echo "Create redis-cli helper at $REDIS_CLI"
+  chmod +x $REDIS_CLI && echo "Create redis-cli helper at $REDIS_CLI"
 fi
 
 if [[ ! -z $API_SECRET_CLI ]]; then
   echo '#!/usr/bin/env bash' > $API_SECRET_CLI &&
   cat .env |grep REDIS >> $API_SECRET_CLI &&
   echo "redis-cli -p \$REDIS_PORT -a \$REDIS_PASSWORD \$* HGET SRS_PLATFORM_SECRET token" >> $API_SECRET_CLI &&
-  chmod +x $API_SECRET_CLI &&
-  echo "Create api-secret helper at $API_SECRET_CLI"
+  chmod +x $API_SECRET_CLI && echo "Create api-secret helper at $API_SECRET_CLI"
 fi
 
diff --git a/mgmt/auto/upgrade_prepare b/mgmt/auto/upgrade_prepare
--- a/mgmt/auto/upgrade_prepare
+++ b/mgmt/auto/upgrade_prepare
@@ -87,6 +87,12 @@ if [[ $? -ne 0 ]]; then echo "Setup git alias failed"; exit 1; fi
 # Setup nginx configuration.
 bash auto/upgrade_nginx $CLOUD
 
+# Compatible with previous redis.
+if [[ ! -f containers/data/redis/dump.rdb && -f /var/lib/redis/dump.rdb ]]; then
+  mkdir -p containers/data/redis && cp /var/lib/redis/dump.rdb containers/data/redis/dump.rdb
+  if [[ $? -ne 0 ]]; then echo "Copy redis database failed"; exit 1; fi
+fi
+
 # Execute script for each run.
 bash auto/foreach_run
 if [[ $? -ne 0 ]]; then echo "Execute for each run script failed"; exit 1; fi
