Refine data directory for docker.

diff --git a/mgmt/auto/init_global b/mgmt/auto/init_global
--- a/mgmt/auto/init_global
+++ b/mgmt/auto/init_global
@@ -6,8 +6,13 @@ echo "Init global script"
 if [[ ! -f containers/data/config/.env ]]; then
   touch .env && mkdir -p containers/data/config &&
   mv .env containers/data/config/.env &&
-  ln -sf containers/data/config/.env .env &&
   echo "Migrate .env to containers/data/config/.env"
   if [[ $? -ne 0 ]]; then echo "MGMT migrate .env failed"; exit 1; fi
+fi
+
+# Because .env might be moved to config, so we link it.
+if [[ ! -f .env ]]; then
+  ln -sf containers/data/config/.env .env
+  if [[ $? -ne 0 ]]; then echo "MGMT link .env failed"; exit 1; fi
 fi
 
