Platform: Refine nginx config with dynamic.

diff --git a/mgmt/auto/upgrade_prepare b/mgmt/auto/upgrade_prepare
--- a/mgmt/auto/upgrade_prepare
+++ b/mgmt/auto/upgrade_prepare
@@ -99,20 +99,36 @@ if [[ -d /etc/nginx/default.d ]]; then
   fi
 
   # For nginx default config.
-  cp containers/conf/nginx.default.conf /etc/nginx/default.d/default.conf && echo "Refresh nginx default.conf ok"
+  rm -f /etc/nginx/default.d/default.conf &&
+  cp containers/conf/nginx.default.conf /etc/nginx/default.d/default.conf &&
+  echo "Refresh nginx default.conf ok"
   if [[ $? -ne 0 ]]; then echo "Refresh nginx default.conf failed"; exit 1; fi
 
   # For nginx mgmt config.
-  cp containers/conf/nginx.mgmt.conf /etc/nginx/default.d/mgmt.conf && echo "Refresh nginx mgmt.conf ok"
+  rm -f /etc/nginx/default.d/mgmt.conf &&
+  cp containers/conf/nginx.mgmt.conf /etc/nginx/default.d/mgmt.conf &&
+  echo "Refresh nginx mgmt.conf ok"
   if [[ $? -ne 0 ]]; then echo "Refresh nginx mgmt.conf failed"; exit 1; fi
 
   # For nginx srs config.
-  cp containers/conf/nginx.srs.conf /etc/nginx/default.d/srs.conf && echo "Refresh nginx srs.conf ok"
+  rm -f /etc/nginx/default.d/srs.conf &&
+  cp containers/conf/nginx.srs.conf /etc/nginx/default.d/srs.conf &&
+  echo "Refresh nginx srs.conf ok"
   if [[ $? -ne 0 ]]; then echo "Refresh nginx srs.conf failed"; exit 1; fi
 
   # For DVR preview, create nginx location.
-  cp containers/conf/nginx.dvr.preview.conf /etc/nginx/default.d/dvr.preview.conf && echo "Refresh nginx dvr.preview.conf ok"
+  rm -f /etc/nginx/default.d/dvr.preview.conf &&
+  cp containers/conf/nginx.dvr.preview.conf /etc/nginx/default.d/dvr.preview.conf &&
+  echo "Refresh nginx dvr.preview.conf ok"
   if [[ $? -ne 0 ]]; then echo "Refresh nginx dvr.preview.conf failed"; exit 1; fi
+
+  # For dynamic config, generated by mgmt.
+  if [[ -f containers/conf/nginx.dynamic.conf ]]; then
+    rm -f /etc/nginx/default.d/nginx.dynamic.conf &&
+    cp containers/conf/nginx.dynamic.conf /etc/nginx/default.d/dynamic.conf &&
+    echo "Refresh nginx dynamic.conf ok"
+    if [[ $? -ne 0 ]]; then echo "Refresh nginx dynamic.conf failed"; exit 1; fi
+  fi
 
   # Reload nginx service.
   systemctl reload nginx && echo "Reload nginx ok"
