Pull target version image for platform.

diff --git a/mgmt/auto/upgrade_containers b/mgmt/auto/upgrade_containers
--- a/mgmt/auto/upgrade_containers
+++ b/mgmt/auto/upgrade_containers
@@ -5,6 +5,12 @@ echo "Update containers script."
 REGISTRY=$1
 if [[ $REGISTRY == '' ]]; then echo "No docker registry"; exit 1; fi
 
+if [[ $TARGET_VERSION == '' ]]; then
+  TARGET_VERSION=$2
+fi
+TAG_NAME=$(echo $TARGET_VERSION|grep '^v')
+echo "The REGISTRY=$REGISTRY TARGET_VERSION=$TARGET_VERSION TAG_NAME=$TAG_NAME"
+
 echo "Update the docker containers."
 docker pull ${REGISTRY}/ossrs/node:slim &&
 docker pull ${REGISTRY}/ossrs/prometheus &&
@@ -73,6 +79,12 @@ if [[ $? -ne 0 ]]; then echo "Upgrade containers failed"; exit 1; fi
 # which has the same hash.
 echo "Update platform image" && docker pull $REGISTRY/ossrs/srs-cloud:platform-1
 if [[ $? -ne 0 ]]; then echo "Update platform image failed"; exit 1; fi
+
+# The target version might not equal to major.
+if [[ $TAG_NAME != '' ]]; then
+  echo "Update platform image $TAG_NAME" && docker pull $REGISTRY/ossrs/srs-cloud:platform-$TAG_NAME
+  if [[ $? -ne 0 ]]; then echo "Update platform image $TAG_NAME failed"; exit 1; fi
+fi
 
 # Removed unreferenced image, the TAG is <none>
 for image in $(docker images |grep '<none>' |awk '{print $3}'); do
