Platform: Refresh systemctl config and reload it.

diff --git a/mgmt/auto/upgrade_prepare b/mgmt/auto/upgrade_prepare
--- a/mgmt/auto/upgrade_prepare
+++ b/mgmt/auto/upgrade_prepare
@@ -94,3 +94,11 @@ bash auto/upgrade_nginx $CLOUD
 bash auto/foreach_run
 if [[ $? -ne 0 ]]; then echo "Execute for each run script failed"; exit 1; fi
 
+# If systemctl config changed, reload it.
+diff usr/lib/systemd/system/srs-cloud.service /usr/lib/systemd/system/srs-cloud.service
+if [[ $? -ne 0 ]]; then
+  cp -f usr/lib/systemd/system/srs-cloud.service /usr/lib/systemd/system/srs-cloud.service &&
+  systemctl daemon-reload
+  if [[ $? -ne 0 ]]; then echo "Update systemctl config failed"; exit 1; fi
+fi
+
