Auto create swap if memory is low

diff --git a/mgmt/auto/upgrade_prepare b/mgmt/auto/upgrade_prepare
--- a/mgmt/auto/upgrade_prepare
+++ b/mgmt/auto/upgrade_prepare
@@ -139,3 +139,7 @@ if [[ $? -ne 0 ]]; then echo "Warning: Setup git alias failed"; exit 1; fi
 yum install -y git gcc-c++ gdb make tree dstat
 if [[ $? -ne 0 ]]; then echo "Install dependencies failed"; exit 1; fi
 
+# Execute script for each run.
+bash auto/foreach_run
+if [[ $? -ne 0 ]]; then echo "Execute for each run script failed"; exit 1; fi
+
diff --git a/mgmt/bootstrap b/mgmt/bootstrap
--- a/mgmt/bootstrap
+++ b/mgmt/bootstrap
@@ -7,5 +7,13 @@ echo "Run srs-terraform at $WORK_DIR from $0"
 APP_ARGS=$@
 echo "Program args: $APP_ARGS"
 
-cd $WORK_DIR && env NODE_ENV=production node --title='srs-terraform listen 2022' index.js $APP_ARGS
+# Do everything at the same work directory.
+cd $WORK_DIR
+
+# Execute script for each run.
+bash auto/foreach_run
+if [[ $? -ne 0 ]]; then echo "Execute for each run script failed"; exit 1; fi
+
+# Start the application server.
+env NODE_ENV=production node --title='srs-terraform listen 2022' index.js $APP_ARGS
 
