Platform: Refine NGINX configuration structure.

diff --git a/mgmt/auto/upgrade_nginx b/mgmt/auto/upgrade_nginx
--- a/mgmt/auto/upgrade_nginx
+++ b/mgmt/auto/upgrade_nginx
@@ -19,14 +19,10 @@ if [[ ! -f containers/ssl/nginx.key && -f /etc/nginx/ssl/nginx.key ]]; then
   if [[ $? -ne 0 ]]; then echo "Setup SSL/TLS files failed"; exit 1; fi
 fi
 
-# Generate self-sign HTTPS crt and file.
-if [[ ! -f containers/ssl/nginx.key ]]; then
-  mkdir -p containers/ssl &&
-  rm -f containers/ssl/nginx.key containers/ssl/nginx.crt &&
-  openssl genrsa -out containers/ssl/nginx.key 2048 &&
-  openssl req -new -x509 -key containers/ssl/nginx.key -out containers/ssl/nginx.crt \
-    -days 3650 -subj "/C=CN/ST=Beijing/L=Beijing/O=Me/OU=Me/CN=ossrs.net"
-  if [[ $? -ne 0 ]]; then echo "Create self-sign cert failed"; exit 1; fi
+# Migrate the previous dynamic config.
+if [[ -f containers/conf/nginx.dynamic.conf && ! -f containers/conf/default.d/nginx.dynamic.conf ]]; then
+  mv containers/conf/nginx.dynamic.conf containers/conf/default.d/nginx.dynamic.conf
+  if [[ $? -ne 0 ]]; then echo "Setup nginx dynamic failed"; exit 1; fi
 fi
 
 # Overwrite the default nginx config.
@@ -41,43 +37,13 @@ if [[ $CLOUD == DO ]];  then
   if [[ $? -ne 0 ]]; then echo "Setup nginx.conf failed"; exit 1; fi
 fi
 
+# Build the mgmt/containers/conf/conf.d/nginx.vhost.conf
+bash auto/setup_vhost
+
 # For nginx server config
-rm -f /etc/nginx/conf.d/server.conf &&
-ln -sf $(pwd)/containers/conf/nginx.server.conf /etc/nginx/conf.d/server.conf &&
-echo "Refresh nginx server.conf ok"
-if [[ $? -ne 0 ]]; then echo "Refresh nginx server.conf failed"; exit 1; fi
-
-# For nginx default config.
-rm -f /etc/nginx/default.d/default.conf &&
-ln -sf $(pwd)/containers/conf/nginx.default.conf /etc/nginx/default.d/default.conf &&
-echo "Refresh nginx default.conf ok"
-if [[ $? -ne 0 ]]; then echo "Refresh nginx default.conf failed"; exit 1; fi
-
-# For nginx mgmt config.
-rm -f /etc/nginx/default.d/mgmt.conf &&
-ln -sf $(pwd)/containers/conf/nginx.mgmt.conf /etc/nginx/default.d/mgmt.conf &&
-echo "Refresh nginx mgmt.conf ok"
-if [[ $? -ne 0 ]]; then echo "Refresh nginx mgmt.conf failed"; exit 1; fi
-
-# For nginx srs config.
-rm -f /etc/nginx/default.d/srs.conf &&
-ln -sf $(pwd)/containers/conf/nginx.srs.conf /etc/nginx/default.d/srs.conf &&
-echo "Refresh nginx srs.conf ok"
-if [[ $? -ne 0 ]]; then echo "Refresh nginx srs.conf failed"; exit 1; fi
-
-# For DVR preview, create nginx location.
-rm -f /etc/nginx/default.d/dvr.preview.conf &&
-ln -sf $(pwd)/containers/conf/nginx.dvr.preview.conf /etc/nginx/default.d/dvr.preview.conf &&
-echo "Refresh nginx dvr.preview.conf ok"
-if [[ $? -ne 0 ]]; then echo "Refresh nginx dvr.preview.conf failed"; exit 1; fi
-
-# For dynamic config, generated by mgmt.
-# Note that we create a empty file here.
-touch containers/conf/nginx.dynamic.conf &&
-rm -f /etc/nginx/default.d/nginx.dynamic.conf &&
-ln -sf $(pwd)/containers/conf/nginx.dynamic.conf /etc/nginx/default.d/dynamic.conf &&
-echo "Refresh nginx dynamic.conf ok"
-if [[ $? -ne 0 ]]; then echo "Refresh nginx dynamic.conf failed"; exit 1; fi
+rm -f /etc/nginx/conf.d/nginx.vhost.conf /etc/nginx/conf.d/server.conf &&
+ln -sf $(pwd)/containers/conf/conf.d/nginx.vhost.conf /etc/nginx/conf.d/vhost.conf
+if [[ $? -ne 0 ]]; then echo "Refresh nginx vhost.conf failed"; exit 1; fi
 
 # Reload nginx service.
 systemctl reload nginx && echo "Reload nginx ok"
