Mgmt: Extract UI to platform.

diff --git a/mgmt/auto/upgrade_ui b/mgmt/auto/upgrade_ui
--- a/mgmt/auto/upgrade_ui
+++ b/mgmt/auto/upgrade_ui
@@ -10,7 +10,9 @@ echo "Make and upgrade updates"
 (cd .. && make upgrade)
 if [[ $? -ne 0 ]]; then echo "Make and install updates failed"; exit 1; fi
 
-echo "Switch to new version"
-(cd ui && TMP_BUILD="build-$(date +%s)" && mv build $TMP_BUILD && mv upgrade build && rm -rf $TMP_BUILD)
-if [[ $? -ne 0 ]]; then echo "Switch to new version failed"; exit 1; fi
+if [[ -d ui/build && -d ui/upgrade ]]; then
+  echo "Switch to new version"
+  (cd ui && TMP_BUILD="build-$(date +%s)" && mv build $TMP_BUILD && mv upgrade build && rm -rf $TMP_BUILD)
+  if [[ $? -ne 0 ]]; then echo "Switch to new version failed"; exit 1; fi
+fi
 
