Platform: Support deliver HLS by NGINX.

diff --git a/mgmt/auto/upgrade_nginx b/mgmt/auto/upgrade_nginx
--- a/mgmt/auto/upgrade_nginx
+++ b/mgmt/auto/upgrade_nginx
@@ -9,7 +9,8 @@ if [[ ! -d /etc/nginx/default.d ]]; then
 fi
 
 # Overwrite the default nginx config.
-cp containers/conf/nginx.conf /etc/nginx/nginx.conf && echo "Refresh nginx.conf ok"
+rm -f /etc/nginx/nginx.conf &&
+ln -sf $(pwd)/containers/conf/nginx.conf /etc/nginx/nginx.conf && echo "Refresh nginx.conf ok"
 if [[ $? -ne 0 ]]; then echo "Refresh nginx.conf failed"; exit 1; fi
 
 # For DO Ubuntu20, use www-data as nginx user.
@@ -21,35 +22,35 @@ fi
 
 # For nginx default config.
 rm -f /etc/nginx/default.d/default.conf &&
-cp containers/conf/nginx.default.conf /etc/nginx/default.d/default.conf &&
+ln -sf $(pwd)/containers/conf/nginx.default.conf /etc/nginx/default.d/default.conf &&
 echo "Refresh nginx default.conf ok"
 if [[ $? -ne 0 ]]; then echo "Refresh nginx default.conf failed"; exit 1; fi
 
 # For nginx mgmt config.
 rm -f /etc/nginx/default.d/mgmt.conf &&
-cp containers/conf/nginx.mgmt.conf /etc/nginx/default.d/mgmt.conf &&
+ln -sf $(pwd)/containers/conf/nginx.mgmt.conf /etc/nginx/default.d/mgmt.conf &&
 echo "Refresh nginx mgmt.conf ok"
 if [[ $? -ne 0 ]]; then echo "Refresh nginx mgmt.conf failed"; exit 1; fi
 
 # For nginx srs config.
 rm -f /etc/nginx/default.d/srs.conf &&
-cp containers/conf/nginx.srs.conf /etc/nginx/default.d/srs.conf &&
+ln -sf $(pwd)/containers/conf/nginx.srs.conf /etc/nginx/default.d/srs.conf &&
 echo "Refresh nginx srs.conf ok"
 if [[ $? -ne 0 ]]; then echo "Refresh nginx srs.conf failed"; exit 1; fi
 
 # For DVR preview, create nginx location.
 rm -f /etc/nginx/default.d/dvr.preview.conf &&
-cp containers/conf/nginx.dvr.preview.conf /etc/nginx/default.d/dvr.preview.conf &&
+ln -sf $(pwd)/containers/conf/nginx.dvr.preview.conf /etc/nginx/default.d/dvr.preview.conf &&
 echo "Refresh nginx dvr.preview.conf ok"
 if [[ $? -ne 0 ]]; then echo "Refresh nginx dvr.preview.conf failed"; exit 1; fi
 
 # For dynamic config, generated by mgmt.
-if [[ -f containers/conf/nginx.dynamic.conf ]]; then
-  rm -f /etc/nginx/default.d/nginx.dynamic.conf &&
-  cp containers/conf/nginx.dynamic.conf /etc/nginx/default.d/dynamic.conf &&
-  echo "Refresh nginx dynamic.conf ok"
-  if [[ $? -ne 0 ]]; then echo "Refresh nginx dynamic.conf failed"; exit 1; fi
-fi
+# Note that we create a empty file here.
+touch containers/conf/nginx.dynamic.conf &&
+rm -f /etc/nginx/default.d/nginx.dynamic.conf &&
+ln -sf $(pwd)/containers/conf/nginx.dynamic.conf /etc/nginx/default.d/dynamic.conf &&
+echo "Refresh nginx dynamic.conf ok"
+if [[ $? -ne 0 ]]; then echo "Refresh nginx dynamic.conf failed"; exit 1; fi
 
 # Reload nginx service.
 systemctl reload nginx && echo "Reload nginx ok"
