Refine workflow. v1.0.302

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,7 +7,25 @@ on:
       - publication-v*
 
 jobs:
+  check-test:
+    steps:
+      - name: Wait for Test Workflow
+        uses: fountainhead/action-wait-for-check@v1.1.0
+        id: wait-for-test
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          checkName: test-final
+          ref: ${{ github.sha }}
+          timeoutSeconds: 3600
+      - name: Check Test Workflow result
+        if: steps.wait-for-test.outputs.conclusion != 'success'
+        run: |
+          echo "Test Workflow failed, aborting release" && exit 1
+    runs-on: ubuntu-20.04
+
   envs:
+    needs:
+      - check-test
     name: envs
     steps:
       # Git checkout
